worlds:
- world

# More storms? or only standard ones?
extraStorms: true

# Duration in ticks
stormDurationMin: 2500
stormDurationMax: 10000

# Time between extra storms
niceWeatherMin: 500
niceWeatherMax: 5000

# Is it impossible to place beds? (but this is rather buggy, so sleep
# prevention is more recommended.)
prohibitBedPlacing: true

# Message to display if a player tries to place a bed
bedPlacingMessage: One can not place beds in the dark of the ethernal night